apps/calendar_app/urls.py
from django.urls import path, include
from . import views

# url patterns
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'), 
    path('event/new/', views.new_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventUpdate.as_view(), name='event_edit'),
    path('event/<int:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
    ]

apps/login_app/urls.py
from xml.etree.ElementInclude import include
from django.urls import path, include
from . import views

app_name = 'login_app'

# url patterns
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login_user', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('tasks', include('apps.todo_list_app.urls')),
    path('calendar', include('apps.calendar_app.urls')),
    path('gallery', include('apps.gallery_app.urls')),
]

myWebSite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.login_app.urls')),
    path('todo_list/', include('apps.todo_list_app.urls')),
    path('calendar/', include('apps.calendar_app.urls')),
    path('gallery/', include('apps.gallery_app.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/calendar_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Event model for an sql table
class Event(models.Model):
    # Each event has an woner (user) - each user can see only their events 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    @property
    def get_html_url(self):
        url = reverse('event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

apps/calendar_app/forms.py
from django.forms import ModelForm, DateInput
from .models import Event

# New calender event form
class EventForm(ModelForm):
  # input_formats to parse HTML5 datetime-local input to datetime field
  input_formats = ['%Y-%m-%dT%H:%M']
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = ['title', 'description', 'start_time', 'end_time']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)

apps/calendar_app/views.py
from datetime import datetime, timedelta
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DeleteView, UpdateView
from django.utils.safestring import mark_safe
# Block unwanted access to views 
from django.contrib.auth.mixins import LoginRequiredMixin
import calendar
from django.contrib import messages
from django.urls import reverse_lazy

from .models import *
from .utils import Calendar
from .forms import EventForm

# Calendar view - uses the utils file
class CalendarView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'calendar_app/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['event'] = new_event(self.request)

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month, self.request.user)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)

        return context

# Calculate the previous month for the calender view
def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

# Calculate the next month for the calender view
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

# Return today's day for the calender view
def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return datetime(year, month, 1)
    return datetime.today()

# A view to create a new calender event
def new_event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    # Uses the forms file
    form = EventForm(request.POST or None, instance=instance)
    # Make sure the user field in the model is the current user   
    form.instance.user = request.user
    # Check for valid information 
    if request.POST and form.is_valid():
        if form.instance.start_time <= form.instance.end_time:
            form.save()
            return HttpResponseRedirect(reverse('calendar'))
        else:
            messages.info(request, "The start time can't be after the end time")
    return render(request, 'calendar_app/new_event.html', {'form': form})

# A class view to update an event
class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['title', 'description', 'start_time', 'end_time']
    template_name = 'calendar_app/update_event.html'
    success_url = reverse_lazy('calendar')

    # Or you can use the function below
    #def get_success_url(self):
    #    return reverse('calendar')

    def get_context_data(self):
        context = super(EventUpdate, self).get_context_data()
        context['event_id'] = self.object.id
        return context

# A class view to delete an event
class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    # You have to use reverse_lazy() instead of reverse(),
    # as the urls are not loaded when the file is imported.
    success_url = reverse_lazy('calendar')

apps/calendar_app/templates/base2.html
<!-- cal/templates/cal/base2.html -->
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'Stylesheet2.css' %}">
    <title>Calendar</title>
</head>
<body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #17a2b8; ">
        <a class="navbar-brand" href="">myCalendar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login_app:index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{user.first_name.capitalize}}</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}
    <br>

    <div class="form-group">
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{message}}
        </div>
        {% endfor %}
    </div>

    <div class="footer2">
        @Copyright myDrive 2022- All Right Reserved.
    </div>
</body>
</html>