apps/login_app/urls.py
from xml.etree.ElementInclude import include
from django.urls import path, include
from . import views

app_name = 'login_app'

# url patterns
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login_user', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('tasks', include('apps.todo_list_app.urls')),
    path('calendar', include('apps.calendar_app.urls')),
    path('gallery', include('apps.gallery_app.urls')),
]

myWebSite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.login_app.urls')),
    path('todo_list/', include('apps.todo_list_app.urls')),
    path('calendar/', include('apps.calendar_app.urls')),
    path('gallery/', include('apps.gallery_app.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/login_app/models.py
from django.db import models

# Create your models here.

apps/login_app/views.py
"""
Definition of views.
"""
from datetime import datetime
from django.shortcuts import render, HttpResponse, redirect
from django.http import HttpRequest
from django.contrib import messages
from django.contrib.auth.models import User, auth

# Main page
def index(request):
    return render(request, 'login_app/index.html')

# Logout a user view
def logout_user(request):
    auth.logout(request)
    return redirect('login_app:index')

# Login a user view
def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('login_app:index')
        else:
            messages.info(request, 'Invalid Username or Password')
            return redirect('login_app:login_user')
    else:
         return render(request, 'login_app/login.html')

# Singup a user view
def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken')
                return redirect('login_app:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already taken')
                return redirect('login_app:register')
            else:
                user = User.objects.create_user(username=username, password=password, 
                                        email=email, first_name=first_name, last_name=last_name)
                user.save()
                
                return redirect('login_app:login_user')
        else:
            messages.info(request, 'Both passwords are not matching')
            return redirect('login_app:register')
    else:
        return render(request, 'login_app/registeration.html')

# Contact view
def contact(request):
    return render(request, 'login_app/contact.html')

# About view
def about(request):
    return render(request, 'login_app/about.html')

apps/login_app/templates/login_app/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>

        .footer {
            position: fixed;
            left: 10px;
            bottom: 5px;
            right: 10px;
            background-color: #424949;
            color: white;
            text-align: center;
        }
    </style>
    <title>About</title>
</head>

<body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #424949;">
        <a class="navbar-brand" href="">About</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login_app:index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{user.first_name.capitalize}}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container my-3">
        <h1 style="text-align:center;">Welcome To myDrive</h1>
    </div>

    <div class="card">
        <div class="card-body" style="text-align:center;">
            <h3>Thanks for landing on this page to know more about myDrive</h3>
            <br>
            <h5>
                This website is created for a project in full-stack web development, It has a to-do-list,
                a calender and a gallery for you to upload your photos.
            </h5>
            <h5>
                This website was created for studies reasons only, but easily can be modify for production purposes.
            </h5>
            <br>
            <h3>For more of my projects please see: <a href="https://github.com/sefi0609">github.com/sefi0609</a></h3>
        </div>
    </div>

    <div class="footer">
        @Copyright myDrive 2022- All Right Reserved.
    </div>
</body>

</html>

apps/login_app/templates/login_app/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>

        .footer {
            position: fixed;
            left: 10px;
            bottom: 5px;
            right: 10px;
            background-color: #424949;
            color: white;
            text-align: center;
        }
    </style>
    <title>Contact</title>
</head>

<body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #424949;">
        <a class="navbar-brand" href="">Contact</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login_app:index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{user.first_name.capitalize}}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container my-3">
        <h1 style="text-align:center;">Welcome To myDrive</h1>
    </div>

    <div class="card">
        <div class="card-body" style="text-align:center;">
            <h3>Thanks for landing on this page for contect information</h3>
            <br>
            <h5>
                For my GitHub visit: <a href="https://github.com/sefi0609">github.com/sefi0609</a>
            </h5>
            <h5>
                For my Linkedin visit: <a href="https://www.linkedin.com/in/yosefi-kroytoro-computer-science/">linkedin.com/in/yosefi-kroytoro-computer-science</a>
            </h5>
            <br>
            <h2>have a great day !</h2>
        </div>

        <div class="footer">
            @Copyright myDrive 2022- All Right Reserved.
        </div>
</body>

</html>

apps/login_app/templates/login_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>

        .footer {
            position: fixed;
            left: 10px;
            bottom: 5px;
            right: 10px;
            background-color: #424949;
            color: white;
            text-align: center;
        }
    </style>
    <title>myDrive</title>
</head>

<body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #424949;">
        <a class="navbar-brand" href="">myDrive</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="">HOME<span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{user.first_name.capitalize}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:logout_user' %}">LOGOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:contact' %}">CONTACT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="tasks">TO-DO-LIST</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="calendar">CALENDER</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="gallery">GALLERY</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:register' %}">SIGN UP</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:login_user' %}">LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:contact' %}">CONTACT</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container my-3">
        <h1 style="text-align:center;">Welcome To myDrive</h1>
    </div>

    <div class="card">
        <div class="card-body" style="text-align:center;">
            <h3>Home Page (please don't judge I'm not an artist)</h3>
            <br>
            <h6>
                Please click on sign up if you are new to our site or login if you already have an account.
            </h6>
            <h6>
                For more information about this site, Please click on About or Contact.
            </h6>
            <br>
            <h2 style="text-align:center;">Hope you anjoy using myWebSite &#128522;</h2>
        </div>

        <div class="footer">
            @Copyright myDrive 2022- All Right Reserved.
        </div>
    </div>
</body>

</html>

apps/login_app/templates/login_app/login.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>

        .footer {
            position: fixed;
            left: 10px;
            bottom: 5px;
            right: 10px;
            background-color: #424949;
            color: white;
            text-align: center;
        }
    </style>
    <title>Login</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #424949;">
        <a class="navbar-brand" href="{% url 'login_app:index' %}">myDrive</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login_app:index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{user.first_name.capitalize}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:logout_user' %}">LOGOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:contact' %}">CONTACT</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:contact' %}">CONTACT</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container my-3">
        <h1 style="text-align:center;">Welcome To myDrive</h1>
    </div>

    <hr>

    <div class="mx-auto" style="width: 300px; text-align:center;">
        <form action="login_user" method="post" class="form-horizontal">
            {% csrf_token%}
            <div class="col-xs-8 col-xs-offset-4">
                <h2>LOGIN</h2>
            </div>

            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
            </div>
            <button type="submit" class="btn btn-primary">LOGIN</button>
            <br />
            <div class="form-group">
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{message}}
                </div>
                {% endfor %}
            </div>
        </form>
    </div>

        <hr>

        <p style="text-align:center;">New to this site? <a href="{% url 'login_app:register' %}">Singup</a></p>

        <div class="footer">
            @Copyright myDrive 2022- All Right Reserved.
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
</body>

</html>

apps/login_app/templates/login_app/logout.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

apps/login_app/templates/login_app/registeration.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>

        .footer {
            position: relative;
            left: 10px;
            bottom: 5px;
            right: 10px;
            margin-right: 20px;
            background-color: #424949;
            color: white;
            text-align: center;
        }
    </style>
    <title>Singup</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #424949;">
        <a class="navbar-brand" href="{% url 'login_app:index' %}">myDrive</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login_app:index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{user.first_name.capitalize}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:logout_user' %}">LOGOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:contact' %}">CONTACT</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:contact' %}">CONTACT</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container my-3">
        <h1 style="text-align:center;">Welcome To myDrive</h1>
    </div>

    <hr>

    <form action="/register" method="POST" class="form-horizontal">
        {% csrf_token%}
        <div class="mx-auto" style="width: 300px;">

            <div class="col-xs-8 col-xs-offset-4">
                <h2 style="text-align:center;">SIGN UP</h2>
            </div>
            <hr />
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username"
                       Required>
            </div>
            <div class="form-group">
                <label for="fanme">First Name</label>
                <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Enter First Name"
                       Required>
            </div>
            <div class="form-group">
                <label for="lname">Last Name</label>
                <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter Last Name"
                       Required>
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" Required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password"
                       Required>
            </div>
            <div class="form-group">
                <label for="confirm_password">Confirm Password</label>
                <input type="password" class="form-control" name="confirm_password" id="confirm_password"
                       placeholder="Confirm Your Password" Required>
            </div>
            <button type="submit" class="btn btn-primary">SIGNUP</button>
            <a class="btn btn-dark" href="{% url 'login_app:login_user' %}" role="button">LOGIN</a>
        </div>
    </form>

    <hr>

    <div class="form-group">
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{message}}
        </div>
        {% endfor %}
    </div>

    <p style="text-align:center;">Already have an account? <a href="{% url 'login_app:login_user' %}">Login</a></p>

    <div class="footer">
        @Copyright myDrive 2022- All Right Reserved.
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>

</html>